{
 "title": "datalab federation summary",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Root fs space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=~\"/\"} / 1000000000",
     "legendFormat": "{{datalab}}"
    }
   ]
  },
  {
   "title": "Data disk space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=~\"/data\"} / 1000000000",
     "legendFormat": "{{datalab}}"
    }
   ]
  },
  {
   "title": "Backups",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "borgmatic_last_archive_original_size_bytes",
     "legendFormat": "{{datalab}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * node_memory_Active_bytes / node_memory_MemTotal_bytes",
     "legendFormat": "{{datalab}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(container_cpu_user_seconds_total{id=\"/\", image=\"\"}[5m]) * 100",
     "legendFormat": "{{datalab}} "
    },
    {
     "expr": "irate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100",
     "legendFormat": "{{datalab}} (container: {{name}})"
    }
   ]
  }
 ]
}