{
 "title": "Matgenix datalab summary",
 "tags": [ "matgenix" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Backup Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "(time() - borgmatic_last_success_timestamp_seconds{datalab=\"avnos\"}) / 3600",
     "legendFormat": "{{datalab}}"
    }
   ]
  },
  {
   "title": "Root fs space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=~\"/\", datalab=\"avnos\"} / 1000000000",
     "legendFormat": "{{datalab}}"
    }
   ]
  },
  {
   "title": "Data disk space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=~\"/data\", datalab=\"avnos\"} / 1000000000",
     "legendFormat": "{{datalab}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{datalab=\"avnos\"}",
     "legendFormat": "{{datalab}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(container_cpu_user_seconds_total{id=\"/\", image=\"\", datalab=\"avnos\"}[5m]) * 100",
     "legendFormat": "{{datalab}} "
    },
    {
     "expr": "irate(container_cpu_user_seconds_total{image!=\"\", datalab=\"avnos\"}[5m]) * 100",
     "legendFormat": "{{datalab}} (container: {{name}})"
    }
   ]
  }
 ]
}